"use client";

/**
 * Quick Start Step 1: What Is This?
 *
 * Introduction to BrennerBot, the Two Axioms, and what the tutorial produces.
 *
 * @see brenner_bot-s797 (Tutorial Path: Quick Start)
 */

import * as React from "react";
import { useRouter } from "next/navigation";
import { motion } from "framer-motion";
import { TutorialStep } from "@/components/tutorial";
import { TutorialCodeBlock, ProTip } from "@/components/tutorial";
import { useTutorial } from "@/lib/tutorial-context";
import type { TutorialStep as TutorialStepType } from "@/lib/tutorial-types";

// ============================================================================
// Step Data
// ============================================================================

const stepData: TutorialStepType = {
  id: "qs-1",
  pathId: "quick-start",
  stepNumber: 1,
  title: "What Is This?",
  estimatedTime: "~3 min",
  whatYouLearn: [
    "Who Sydney Brenner was and why his method matters",
    "The Two Axioms that ground discriminative research",
    "What you'll produce by the end of this tutorial",
  ],
  whatYouDo: [
    "Read the introduction to BrennerBot",
    "Understand the Two Axioms",
    "Preview the research artifact you'll create",
  ],
  troubleshooting: [
    {
      problem: "This feels too abstract",
      solution: "Skim the sample artifact below to see the concrete output you’re aiming for.",
    },
    {
      problem: "Unsure if your question fits",
      solution: "Pick a question where different answers would change what you do next (experiment, decision, or model).",
    },
  ],
};

// ============================================================================
// Main Component
// ============================================================================

export default function QuickStartStep1() {
  const router = useRouter();
  const tutorial = useTutorial();

  React.useEffect(() => {
    tutorial.setPath("quick-start", 7);
    tutorial.goToStep(0);
  }, [tutorial]);

  return (
    <TutorialStep
      step={stepData}
      totalSteps={7}
      disableBack
      onNext={() => {
        tutorial.completeAndAdvance();
        router.push("/tutorial/quick-start/2");
      }}
    >
      {/* Introduction */}
      <section className="space-y-6">
        <div className="p-6 rounded-2xl bg-gradient-to-br from-primary/5 via-primary/10 to-accent/5 border border-primary/20">
          <h2 className="text-xl font-semibold mb-4">What Is BrennerBot?</h2>
          <p className="text-muted-foreground leading-relaxed mb-4">
            <strong className="text-foreground">Sydney Brenner</strong> (1927-2019) was one of the most
            successful experimental biologists in history. He won the Nobel Prize for his work on
            programmed cell death and helped decode the genetic code. But his <em>method</em> is more
            valuable than any single discovery.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            <strong className="text-foreground">BrennerBot</strong> operationalizes that method for
            AI-assisted research. It helps you develop hypotheses that can actually be tested,
            design experiments that discriminate between alternatives, and think rigorously about
            what you&apos;re assuming.
          </p>
        </div>

        {/* The Two Axioms */}
        <div className="space-y-4">
          <h2 className="text-xl font-semibold">The Two Axioms</h2>
          <p className="text-muted-foreground">
            Brenner&apos;s methodology rests on two foundational beliefs:
          </p>

          <div className="grid gap-4 sm:grid-cols-2">
            <motion.div
              className="p-5 rounded-xl border border-primary/30 bg-card"
              whileHover={{ scale: 1.02 }}
              transition={{ type: "spring", stiffness: 300 }}
            >
              <div className="flex items-center gap-3 mb-3">
                <span className="flex items-center justify-center size-8 rounded-lg bg-primary/10 text-primary font-bold">
                  1
                </span>
                <h3 className="font-semibold">Reality has a generative grammar</h3>
              </div>
              <p className="text-sm text-muted-foreground leading-relaxed">
                The world is produced by causal machinery with discoverable rules.
                Phenomena aren&apos;t random — they&apos;re generated by underlying mechanisms
                that we can identify and understand.
              </p>
            </motion.div>

            <motion.div
              className="p-5 rounded-xl border border-accent/30 bg-card"
              whileHover={{ scale: 1.02 }}
              transition={{ type: "spring", stiffness: 300 }}
            >
              <div className="flex items-center gap-3 mb-3">
                <span className="flex items-center justify-center size-8 rounded-lg bg-accent/10 text-accent font-bold">
                  2
                </span>
                <h3 className="font-semibold">To understand is to reconstruct</h3>
              </div>
              <p className="text-sm text-muted-foreground leading-relaxed">
                You haven&apos;t explained something until you can build it from primitives.
                Description isn&apos;t explanation — you need to specify the mechanism that
                produces the phenomenon.
              </p>
            </motion.div>
          </div>
        </div>

        {/* What You'll Produce */}
        <div className="space-y-4">
          <h2 className="text-xl font-semibold">What You&apos;ll Produce</h2>
          <p className="text-muted-foreground">
            By the end of this tutorial, you&apos;ll have a <strong className="text-foreground">research artifact</strong> for
            your own scientific question. Here&apos;s what it contains:
          </p>

          <div className="space-y-3">
            {[
              {
                title: "Hypothesis Slate",
                desc: "2-5 competing explanations, including a genuine \"third alternative\"",
              },
              {
                title: "Discriminative Tests",
                desc: "Tests designed to separate hypotheses, not just confirm your favorite",
              },
              {
                title: "Assumption Ledger",
                desc: "Explicit load-bearing beliefs that your hypotheses depend on",
              },
              {
                title: "Adversarial Critique",
                desc: "Attacks on your own framing to strengthen your thinking",
              },
            ].map((item, i) => (
              <div
                key={i}
                className="flex items-start gap-3 p-3 rounded-lg bg-muted/30 border border-border/50"
              >
                <span className="flex items-center justify-center size-6 rounded-full bg-[oklch(0.72_0.19_145/0.15)] text-[oklch(0.72_0.19_145)] text-xs font-bold shrink-0 mt-0.5">
                  {i + 1}
                </span>
                <div>
                  <p className="font-medium text-foreground">{item.title}</p>
                  <p className="text-sm text-muted-foreground">{item.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        <ProTip>
          You don&apos;t need any AI subscriptions for this tutorial. The Quick Start path works
          with any AI chat interface — Claude, ChatGPT, Gemini, even free tiers. You&apos;ll compose
          prompts locally and paste them into your preferred AI.
        </ProTip>

        {/* Sample Artifact Preview */}
        <div className="space-y-4">
          <h2 className="text-xl font-semibold">Sample Artifact Preview</h2>
          <p className="text-muted-foreground">
            Here&apos;s a snippet of what a completed research artifact looks like:
          </p>

          <TutorialCodeBlock
            code={`# Research Artifact: Cell Fate Determination

## Hypothesis Slate

### H1: Morphogen Gradient Model
Cells determine their fate by reading concentration gradients
of signaling molecules (morphogens) secreted from organizing centers.
- Mechanism: Concentration-dependent transcription factor activation
- Anchors: §58, §78

### H2: Timing Model
Cell fate is determined by intrinsic timing mechanisms that
count cell divisions or developmental stages.
- Mechanism: Sequential gene expression programs
- Anchors: §161

### H3: Third Alternative (Stochastic + Selection)
Initial fate assignment is stochastic, with selection
mechanisms eliminating "incorrect" outcomes.
- Mechanism: Random differentiation + competitive survival
- Anchors: §203

## Discriminative Tests
...`}
            language="markdown"
            title="my_artifact.md"
          />
        </div>

        {/* Next Step Preview */}
        <div className="p-4 rounded-xl border border-border bg-card/50">
          <p className="text-sm text-muted-foreground">
            <strong className="text-foreground">Next up:</strong> In Step 2, you&apos;ll verify
            your prerequisites — Git, terminal access, and Bun. It only takes a couple of minutes.
          </p>
        </div>
      </section>
    </TutorialStep>
  );
}
